### ISSUE TITLE
Missing linux build

### ISSUE THREAD

**Issue by vladsavelyev** [conda-forge/lzstring-feedstock#4]
Version 1.0.4 is not built for linux: https://anaconda.org/conda-forge/lzstring/files 

This is the first version to be built for py3.7, preventing from upgrading to py3.7 for all packages that depend on lzstring.

**Comment by ewels** [comment]
Thanks Vlad - any idea why?

**Comment by vladsavelyev** [comment]
Have not yet figured. I rebuild it manually and it worked. The related PR https://github.com/conda-forge/lzstring-feedstock/pull/3 seems to be populated by robots.

**Comment by vladsavelyev** [comment]
osx and linux build seems to be built by different CIs, osx through Travis, and linux through CircleCI (I guess it's normal for conda-forge) 

And CircleCI build was last time triggered 2 years ago: https://circleci.com/gh/conda-forge/lzstring-feedstock. Trying to re-trigger CI.

**Comment by ewels** [comment]
@conda-gorge/staged-recipes - does anyone have any idea why CircleCI isn’t triggering for Linux builds here? Thanks!

**Comment by ewels** [comment]
@conda-forge/staged-recipes - any idea why CircleCI is not triggering for Linux builds here? Thanks!

**Comment by chrisburr** [comment]
I think Azure is now being used instead.

**Comment by ewels** [comment]
Thanks for the help all!

**Comment by vladsavelyev** [comment]
Thanks for the work, Phil, @dbast, and all!
